/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ModernMermaidPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// types/index.ts
var DEFAULT_SETTINGS = {
  mermaidVersion: "Not loaded",
  transparentMerBackground: true,
  includeBackgroundInCopy: true,
  enablePanZoom: true,
  doubleClickZoomLevel: 2
};

// services/settings-manager.ts
var SettingsManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.settings = DEFAULT_SETTINGS;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.plugin.loadData());
  }
  async saveSettings() {
    await this.plugin.saveData(this.settings);
  }
  getSettings() {
    return this.settings;
  }
  updateSettings(settings) {
    this.settings = { ...this.settings, ...settings };
  }
};

// services/mermaid-loader.ts
var MermaidLoader = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.mermaidLoaded = false;
    this.mermaidLoading = false;
    this.mermaidLoadPromise = null;
    this.pluginMermaidInstance = null;
    this.settingsManager = new SettingsManager(plugin);
  }
  async initializeMermaid() {
    if (this.mermaidLoaded) {
      return;
    }
    if (this.mermaidLoading) {
      if (this.mermaidLoadPromise) {
        await this.mermaidLoadPromise;
      }
      return;
    }
    this.mermaidLoading = true;
    this.mermaidLoadPromise = this.loadMermaid();
    try {
      await this.mermaidLoadPromise;
      this.mermaidLoaded = true;
    } finally {
      this.mermaidLoading = false;
      this.mermaidLoadPromise = null;
    }
  }
  async loadMermaid() {
    console.log("Loading Mermaid...");
    const cached = this.getCache();
    if (cached) {
      console.log("Using cached Mermaid version:", cached.version);
      try {
        await this.loadMermaidFromCode(cached.code, cached.version);
        console.log("Cached Mermaid loaded successfully");
        this.getLatestVersion().then((latestVersion) => {
          if (latestVersion !== cached.version) {
            console.log("New version available:", latestVersion, "- will update");
            this.fetchAndLoadLatest(latestVersion).catch((err) => {
              console.error("Background update failed:", err);
            });
          }
        }).catch((err) => {
          console.error("Failed to check latest version:", err);
        });
        return;
      } catch (error) {
        console.error("Failed to load cached Mermaid:", error);
        this.clearCache();
      }
    }
    console.log("No cache available, fetching latest version");
    try {
      const latestVersion = await this.getLatestVersion();
      await this.fetchAndLoadLatest(latestVersion);
      console.log("Latest Mermaid loaded successfully");
    } catch (error) {
      console.error("Failed to load any Mermaid version:", error);
      throw new Error("Mermaid\uB97C \uB85C\uB4DC\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. \uC778\uD130\uB137 \uC5F0\uACB0\uC744 \uD655\uC778\uD558\uC138\uC694.");
    }
  }
  async getLatestVersion() {
    console.log("Fetching latest Mermaid version...");
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5e3);
    try {
      const response = await fetch("https://registry.npmjs.org/mermaid/latest", {
        signal: controller.signal
      });
      const data = await response.json();
      console.log("Latest version:", data.version);
      return data.version;
    } catch (error) {
      console.error("Failed to fetch latest version:", error);
      throw error;
    } finally {
      clearTimeout(timeout);
    }
  }
  getCache() {
    try {
      const version = localStorage.getItem("modern-mermaid-cached-version");
      const code = localStorage.getItem("modern-mermaid-cached-code");
      if (version && code) {
        return { version, code };
      }
      return null;
    } catch (error) {
      console.error("Failed to load cache:", error);
      return null;
    }
  }
  saveCache(version, code) {
    try {
      localStorage.setItem("modern-mermaid-cached-version", version);
      localStorage.setItem("modern-mermaid-cached-code", code);
    } catch (error) {
      console.error("Failed to save cache:", error);
    }
  }
  clearCache() {
    try {
      localStorage.removeItem("modern-mermaid-cached-version");
      localStorage.removeItem("modern-mermaid-cached-code");
    } catch (error) {
      console.error("Failed to clear cache:", error);
    }
  }
  async fetchAndLoadLatest(version) {
    try {
      const code = await this.fetchMermaidCode(version);
      await this.loadMermaidFromCode(code, version);
      this.saveCache(version, code);
      const { Notice: Notice2 } = await import("obsidian");
      new Notice2(`Mermaid v${version} \uC5C5\uB370\uC774\uD2B8 \uC644\uB8CC`);
    } catch (error) {
      console.error("Failed to fetch and load latest Mermaid:", error);
      throw error;
    }
  }
  async fetchMermaidCode(version) {
    console.log(`Fetching Mermaid code for version ${version}...`);
    const url = `https://cdn.jsdelivr.net/npm/mermaid@${version}/dist/mermaid.min.js`;
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 3e4);
    try {
      const response = await fetch(url, { signal: controller.signal });
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const code = await response.text();
      console.log(`Mermaid code fetched successfully (${code.length} chars)`);
      return code;
    } catch (error) {
      console.error("Failed to fetch Mermaid code:", error);
      throw error;
    } finally {
      clearTimeout(timeout);
    }
  }
  async loadMermaidFromCode(code, version) {
    console.log(`Loading Mermaid ${version} into DOM...`);
    this.cleanupExistingScript();
    return new Promise((resolve, reject) => {
      const blob = new Blob([code], { type: "application/javascript" });
      const url = URL.createObjectURL(blob);
      const script = document.createElement("script");
      script.src = url;
      script.id = "mermaid-dynamic-script";
      const timeout = setTimeout(() => {
        console.warn("Mermaid load timeout, checking if available anyway...");
        URL.revokeObjectURL(url);
        if (this.pluginMermaidInstance) {
          try {
            this.pluginMermaidInstance.initialize({ startOnLoad: false });
            resolve();
          } catch (e) {
            reject(new Error("Mermaid initialization failed"));
          }
        } else {
          reject(new Error("Mermaid not loaded after timeout"));
        }
      }, 6e4);
      script.onload = () => {
        console.log("Mermaid script loaded, checking for mermaid object...");
        clearTimeout(timeout);
        URL.revokeObjectURL(url);
        const mermaid = window.mermaid;
        if (mermaid) {
          console.log("Mermaid object found, initializing...");
          this.pluginMermaidInstance = mermaid;
          try {
            mermaid.initialize({ startOnLoad: false });
            console.log("Mermaid initialized successfully");
            resolve();
          } catch (e) {
            console.error("Mermaid initialization failed:", e);
            reject(new Error("Mermaid initialization failed"));
          }
        } else {
          console.error("Mermaid object not found after load");
          reject(new Error("Mermaid not loaded"));
        }
      };
      script.onerror = () => {
        clearTimeout(timeout);
        URL.revokeObjectURL(url);
        console.error("Script error occurred");
        reject(new Error("Failed to load Mermaid from code"));
      };
      console.log("Appending script to head...");
      document.head.appendChild(script);
    });
  }
  cleanupExistingScript() {
    const existingScript = document.getElementById("mermaid-dynamic-script");
    if (existingScript) {
      existingScript.remove();
    }
    delete window.mermaid;
    this.pluginMermaidInstance = null;
  }
  cleanup() {
    this.cleanupExistingScript();
  }
  getMermaidInstance() {
    return this.pluginMermaidInstance;
  }
  async updateVersion(version) {
    if (this.pluginMermaidInstance) {
      this.settingsManager.updateSettings({ mermaidVersion: version });
      await this.settingsManager.saveSettings();
    }
  }
};

// ui/pan-zoom-handler.ts
var PanZoomHandler = class {
  constructor(wrapper, svgElement, settings) {
    this.wrapper = wrapper;
    this.svgElement = svgElement;
    this.settings = settings;
    this.state = {
      scale: 1,
      translateX: 0,
      translateY: 0,
      panning: false,
      startX: 0,
      startY: 0,
      pointX: 0,
      pointY: 0
    };
    this.isPanningActive = false;
    this.handleMouseDown = (e) => {
      e.preventDefault();
      this.state.startX = e.clientX - this.state.translateX;
      this.state.startY = e.clientY - this.state.translateY;
      this.state.panning = true;
      this.isPanningActive = true;
      this.wrapper.style.cursor = "grabbing";
      window.addEventListener("mousemove", this.handleWindowMouseMove);
      window.addEventListener("mouseup", this.handleWindowMouseUp);
    };
    this.handleWindowMouseUp = () => {
      this.state.panning = false;
      this.isPanningActive = false;
      this.wrapper.style.cursor = "grab";
      window.removeEventListener("mousemove", this.handleWindowMouseMove);
      window.removeEventListener("mouseup", this.handleWindowMouseUp);
    };
    this.handleWindowMouseMove = (e) => {
      if (!this.state.panning)
        return;
      e.preventDefault();
      this.state.translateX = e.clientX - this.state.startX;
      this.state.translateY = e.clientY - this.state.startY;
      this.updateTransform();
    };
    this.handleWheel = (e) => {
      const delta = -Math.sign(e.deltaY);
      const currentScale = this.state.scale;
      if (e.ctrlKey || e.metaKey) {
        e.preventDefault();
        const newScale = Math.min(Math.max(1, currentScale + delta * 0.05), 3);
        if (newScale === currentScale) {
          return;
        }
        if (!this.svgElement) {
          return;
        }
        const wrapperRect = this.wrapper.getBoundingClientRect();
        const mouseX = e.clientX - wrapperRect.left;
        const mouseY = e.clientY - wrapperRect.top;
        const mouseXInSVG = (mouseX - this.state.translateX) / currentScale;
        const mouseYInSVG = (mouseY - this.state.translateY) / currentScale;
        this.state.scale = newScale;
        this.state.translateX = mouseX - mouseXInSVG * newScale;
        this.state.translateY = mouseY - mouseYInSVG * newScale;
        this.updateTransform();
      }
    };
    this.handleDoubleClick = (e) => {
      e.preventDefault();
      const currentScale = this.state.scale;
      const targetScale = currentScale === 1 ? this.settings.doubleClickZoomLevel : 1;
      if (targetScale === 1) {
        this.state.scale = 1;
        this.state.translateX = 0;
        this.state.translateY = 0;
        this.updateTransform(true);
        return;
      }
      if (!this.svgElement) {
        return;
      }
      const svgRect = this.svgElement.getBoundingClientRect();
      const mouseX = e.clientX - svgRect.left;
      const mouseY = e.clientY - svgRect.top;
      const mouseXInSVG = (mouseX - this.state.translateX) / currentScale;
      const mouseYInSVG = (mouseY - this.state.translateY) / currentScale;
      this.state.scale = targetScale;
      this.state.translateX = mouseX - mouseXInSVG * targetScale;
      this.state.translateY = mouseY - mouseYInSVG * targetScale;
      this.updateTransform(true);
    };
    if (this.svgElement) {
      this.svgElement.style.transformOrigin = "0 0";
    }
  }
  setup() {
    this.wrapper.addEventListener("mousedown", this.handleMouseDown);
    this.wrapper.addEventListener("wheel", this.handleWheel);
    this.wrapper.addEventListener("dblclick", this.handleDoubleClick);
  }
  destroy() {
    if (this.isPanningActive) {
      window.removeEventListener("mousemove", this.handleWindowMouseMove);
      window.removeEventListener("mouseup", this.handleWindowMouseUp);
    }
    this.wrapper.removeEventListener("mousedown", this.handleMouseDown);
    this.wrapper.removeEventListener("wheel", this.handleWheel);
    this.wrapper.removeEventListener("dblclick", this.handleDoubleClick);
  }
  updateTransform(withTransition = false) {
    if (this.svgElement) {
      this.svgElement.style.transition = withTransition ? "transform 0.2s ease-out" : "";
      this.svgElement.style.transform = `translate(${this.state.translateX}px, ${this.state.translateY}px) scale(${this.state.scale})`;
    }
  }
  zoomIn() {
    this.state.scale = Math.min(3, this.state.scale + 0.2);
    this.updateTransform();
  }
  zoomOut() {
    this.state.scale = Math.max(1, this.state.scale - 0.2);
    this.updateTransform();
  }
  reset() {
    this.state.scale = 1;
    this.state.translateX = 0;
    this.state.translateY = 0;
    this.updateTransform();
  }
  getState() {
    return { ...this.state };
  }
};

// ui/controls/button-helper.ts
var BUTTON_STYLES = {
  button: {
    padding: "6px",
    backgroundColor: "rgba(128, 128, 128, 0.1)",
    color: "currentColor",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    opacity: "0.7"
  },
  hover: {
    backgroundColor: "rgba(128, 128, 128, 0.2)",
    opacity: "1"
  }
};
function createControlButton(container, options) {
  const btn = document.createElement("button");
  btn.innerHTML = options.icon;
  const mouseEnterHandler = () => {
    Object.assign(btn.style, BUTTON_STYLES.hover);
  };
  const mouseLeaveHandler = () => {
    if (options.isActive) {
      btn.style.backgroundColor = "rgba(59, 130, 246, 0.2)";
      btn.style.opacity = "1";
    } else {
      Object.assign(btn.style, BUTTON_STYLES.button);
    }
  };
  const clickHandler = () => {
    if (options.onClickLabel) {
      console.log(options.onClickLabel);
    }
    options.onClick();
  };
  Object.assign(btn.style, BUTTON_STYLES.button);
  if (options.isActive) {
    btn.style.backgroundColor = "rgba(59, 130, 246, 0.2)";
    btn.style.opacity = "1";
  }
  btn.addEventListener("mouseenter", mouseEnterHandler);
  btn.addEventListener("mouseleave", mouseLeaveHandler);
  btn.addEventListener("click", clickHandler);
  container.appendChild(btn);
  const cleanup = () => {
    btn.removeEventListener("mouseenter", mouseEnterHandler);
    btn.removeEventListener("mouseleave", mouseLeaveHandler);
    btn.removeEventListener("click", clickHandler);
    btn.remove();
  };
  return { button: btn, cleanup };
}

// ui/mermaid-renderer.ts
var COPY_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>`;
var SUCCESS_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>`;
var ERROR_ICON = `<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>`;
var _MermaidRenderer = class {
  constructor(mermaid, settings) {
    this.mermaid = mermaid;
    this.settings = settings;
    this.timeoutIds = /* @__PURE__ */ new Set();
    this.zoomControlsCleanup = null;
  }
  static cleanupAllHandlers() {
    for (const handler of _MermaidRenderer.activeHandlers) {
      handler.destroy();
    }
    _MermaidRenderer.activeHandlers.clear();
  }
  async render(source, el, theme, backgroundColor) {
    const { width, height, source: actualSource } = this.parseDimensions(source);
    const id = "mermaid-" + Math.random().toString(36).substr(2, 9);
    const themeConfig = theme === "dark" ? "dark" : "default";
    this.mermaid.initialize({ startOnLoad: false, theme: themeConfig });
    let svg;
    try {
      const result = await this.mermaid.render(id, actualSource);
      svg = result.svg;
    } catch (renderError) {
      console.error("Mermaid render error:", renderError);
      this.renderMermaidError(el, renderError.message);
      return;
    }
    if (this.settings.enablePanZoom) {
      this.renderWithPanZoom(svg, el);
    } else {
      this.renderWithoutPanZoom(svg, el);
    }
    this.applyStyles(el, backgroundColor, width, height);
    this.addCopyButton(el, backgroundColor);
  }
  renderWithPanZoom(svg, el) {
    if (this.zoomControlsCleanup) {
      this.zoomControlsCleanup();
    }
    const wrapper = document.createElement("div");
    wrapper.innerHTML = svg;
    wrapper.style.cursor = "grab";
    wrapper.style.userSelect = "none";
    wrapper.style.display = "inline-block";
    wrapper.style.textAlign = "center";
    el.innerHTML = "";
    el.appendChild(wrapper);
    const svgElement = wrapper.querySelector("svg");
    if (svgElement) {
      svgElement.style.transition = "transform 0.1s ease-out";
      svgElement.style.display = "block";
      svgElement.style.margin = "0 auto";
      const svgWidth = svgElement.getAttribute("width");
      const svgHeight = svgElement.getAttribute("height");
      if (svgWidth) {
        wrapper.style.width = svgWidth;
      }
      if (svgHeight) {
        wrapper.style.height = svgHeight;
      }
    }
    const existingHandler = _MermaidRenderer.panZoomHandlers.get(wrapper);
    if (existingHandler) {
      existingHandler.destroy();
      _MermaidRenderer.activeHandlers.delete(existingHandler);
    }
    const panZoomHandler = new PanZoomHandler(wrapper, svgElement, this.settings);
    panZoomHandler.setup();
    _MermaidRenderer.panZoomHandlers.set(wrapper, panZoomHandler);
    _MermaidRenderer.activeHandlers.add(panZoomHandler);
    this.addZoomControls(panZoomHandler, el);
  }
  renderWithoutPanZoom(svg, el) {
    el.innerHTML = svg;
    const svgElement = el.querySelector("svg");
    if (svgElement) {
      svgElement.style.display = "block";
      svgElement.style.margin = "0 auto";
    }
  }
  addZoomControls(panZoomHandler, el) {
    const controlsDiv = document.createElement("div");
    controlsDiv.style.position = "absolute";
    controlsDiv.style.bottom = "8px";
    controlsDiv.style.right = "8px";
    controlsDiv.style.display = "flex";
    controlsDiv.style.gap = "4px";
    controlsDiv.style.zIndex = "10";
    const cleanups = [];
    const { button: btn1, cleanup: cleanup1 } = createControlButton(controlsDiv, {
      icon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/><path d="m8 11 2 2"/><path d="m11 8 2 2"/><path d="m14 11 2 2"/><path d="m11 14 2 2"/><path d="m8 11-2-2"/><path d="m11 8-2-2"/><path d="m14 11-2-2"/><path d="m11 14-2-2"/></svg>`,
      onClick: () => panZoomHandler.zoomOut()
    });
    cleanups.push(cleanup1);
    const { button: btn2, cleanup: cleanup2 } = createControlButton(controlsDiv, {
      icon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/><path d="m9 9 3 3"/><path d="m9 12 3 3"/><path d="m12 9 3 3"/><path d="m12 12 3 3"/></svg>`,
      onClick: () => panZoomHandler.zoomIn()
    });
    cleanups.push(cleanup2);
    const { button: btn3, cleanup: cleanup3 } = createControlButton(controlsDiv, {
      icon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/><path d="M12 17h6"/><path d="M12 21h6"/><path d="M12 7h6"/></svg>`,
      onClick: () => panZoomHandler.reset()
    });
    cleanups.push(cleanup3);
    el.appendChild(controlsDiv);
    this.zoomControlsCleanup = () => {
      cleanups.forEach((cleanup) => cleanup());
      controlsDiv.remove();
    };
  }
  applyStyles(el, backgroundColor, width, height) {
    if (backgroundColor !== "transparent") {
      el.style.backgroundColor = backgroundColor;
    }
    el.style.padding = "20px";
    el.style.borderRadius = "8px";
    el.style.display = "flex";
    el.style.justifyContent = "center";
    el.style.position = "relative";
    if (width) {
      el.style.width = `${width}px`;
      el.style.overflowX = "auto";
    }
    if (height) {
      el.style.height = `${height}px`;
      el.style.overflowY = "auto";
    }
  }
  parseDimensions(source) {
    var _a, _b;
    const lines = source.split("\n");
    const firstLine = lines[0].trim();
    const parts = firstLine.split(",");
    const widthPart = (_a = parts[0]) == null ? void 0 : _a.trim();
    const heightPart = (_b = parts[1]) == null ? void 0 : _b.trim();
    const width = widthPart ? parseInt(widthPart, 10) : null;
    const height = heightPart ? parseInt(heightPart, 10) : null;
    if (width || height) {
      return { width, height, source: lines.slice(1).join("\n").trimStart() };
    }
    return { width: null, height: null, source };
  }
  renderMermaidError(el, errorMessage) {
    el.innerHTML = `
			<div style="padding: 20px; color: #ef4444; border: 1px solid #ef4444; border-radius: 8px; background-color: rgba(239, 68, 68, 0.1);">
				<strong>Mermaid Rendering Error</strong><br><br>
				${errorMessage}<br><br>
				<small style="color: #6b7280;">Make sure you're using a valid Mermaid diagram type (e.g., graph, sequence, gantt, class, state, er, pie, journey, gitgraph, mindmap, timeline, sankey, block, architecture, requirement)</small>
			</div>
		`;
  }
  extractSvgFromElement(el) {
    const svgElement = el.querySelector("svg");
    if (!svgElement) {
      return null;
    }
    svgElement.setAttribute("xmlns", "http://www.w3.org/2000/svg");
    return svgElement;
  }
  convertSvgToDataUrl(svgElement) {
    const svgData = new XMLSerializer().serializeToString(svgElement);
    const base64Svg = btoa(unescape(encodeURIComponent(svgData)));
    return "data:image/svg+xml;base64," + base64Svg;
  }
  renderSvgToCanvas(url, svgElement, backgroundColor) {
    return new Promise((resolve, reject) => {
      const canvas = document.createElement("canvas");
      const img = new Image();
      const cleanup = () => {
        img.onload = null;
        img.onerror = null;
        img.src = "";
      };
      img.onload = () => {
        try {
          const bbox = svgElement.getBoundingClientRect();
          canvas.width = Math.ceil((bbox.width || img.width) * 2);
          canvas.height = Math.ceil((bbox.height || img.height) * 2);
          const ctx = canvas.getContext("2d");
          if (!ctx) {
            cleanup();
            throw new Error("Canvas context is null");
          }
          if (this.settings.includeBackgroundInCopy && backgroundColor !== "transparent") {
            ctx.fillStyle = backgroundColor;
            ctx.fillRect(0, 0, canvas.width, canvas.height);
          }
          ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
          canvas.toBlob((blob) => {
            cleanup();
            if (blob) {
              resolve(blob);
            } else {
              reject(new Error("Blob creation failed"));
            }
          }, "image/png");
        } catch (drawErr) {
          cleanup();
          reject(drawErr);
        }
      };
      img.onerror = () => {
        cleanup();
        reject(new Error("Image load failed"));
      };
      img.src = url;
    });
  }
  async writeBlobToClipboard(blob) {
    await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
  }
  async copySvgToClipboard(el, backgroundColor) {
    const svgElement = this.extractSvgFromElement(el);
    if (!svgElement) {
      throw new Error("SVG element not found");
    }
    const url = this.convertSvgToDataUrl(svgElement);
    const blob = await this.renderSvgToCanvas(url, svgElement, backgroundColor);
    await this.writeBlobToClipboard(blob);
  }
  showCopyFeedback(button, icon, color, timeout) {
    button.innerHTML = icon;
    button.style.color = color;
    const timeoutId = window.setTimeout(() => {
      button.innerHTML = COPY_ICON;
      button.style.color = "currentColor";
      this.timeoutIds.delete(timeoutId);
    }, timeout);
    this.timeoutIds.add(timeoutId);
  }
  async handleCopyClick(el, button, backgroundColor) {
    const originalIcon = button.innerHTML;
    try {
      await this.copySvgToClipboard(el, backgroundColor);
      this.showCopyFeedback(button, SUCCESS_ICON, "#10b981", 1e3);
    } catch (err) {
      console.error("Copy failed:", err);
      this.showCopyFeedback(button, ERROR_ICON, "#ef4444", 1500);
    }
  }
  createCopyButtonElement() {
    const button = document.createElement("button");
    button.innerHTML = COPY_ICON;
    button.style.position = "absolute";
    button.style.top = "8px";
    button.style.left = "8px";
    button.style.padding = "6px";
    button.style.backgroundColor = "rgba(128, 128, 128, 0.1)";
    button.style.color = "currentColor";
    button.style.border = "none";
    button.style.borderRadius = "6px";
    button.style.cursor = "pointer";
    button.style.zIndex = "10";
    button.style.transition = "all 0.2s ease";
    button.style.opacity = "0.7";
    return button;
  }
  setupCopyButtonEvents(button, el, backgroundColor) {
    const mouseEnterHandler = () => {
      button.style.backgroundColor = "rgba(128, 128, 128, 0.2)";
      button.style.opacity = "1";
    };
    const mouseLeaveHandler = () => {
      button.style.backgroundColor = "rgba(128, 128, 128, 0.1)";
      button.style.opacity = "0.7";
    };
    const clickHandler = async () => {
      if (!document.contains(button)) {
        return;
      }
      await this.handleCopyClick(el, button, backgroundColor);
    };
    button.addEventListener("mouseenter", mouseEnterHandler);
    button.addEventListener("mouseleave", mouseLeaveHandler);
    button.addEventListener("click", clickHandler);
  }
  addCopyButton(el, backgroundColor) {
    const button = this.createCopyButtonElement();
    this.setupCopyButtonEvents(button, el, backgroundColor);
    el.appendChild(button);
  }
  cleanup() {
    for (const timeoutId of this.timeoutIds) {
      clearTimeout(timeoutId);
    }
    this.timeoutIds.clear();
    if (this.zoomControlsCleanup) {
      this.zoomControlsCleanup();
      this.zoomControlsCleanup = null;
    }
  }
};
var MermaidRenderer = _MermaidRenderer;
MermaidRenderer.panZoomHandlers = /* @__PURE__ */ new WeakMap();
MermaidRenderer.activeHandlers = /* @__PURE__ */ new Set();

// main.ts
var ModernMermaidPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.unhandledRejectionHandler = null;
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    console.log("Modern Mermaid plugin loading...");
    this.settingsManager = new SettingsManager(this);
    this.mermaidLoader = new MermaidLoader(this);
    await this.settingsManager.loadSettings();
    this.settings = this.settingsManager.getSettings();
    this.addSettingTab(new ModernMermaidSettingTab(this.app, this));
    this.unhandledRejectionHandler = (event) => {
      if (event.reason && event.reason.message && event.reason.message.includes("mermaid")) {
        console.error("Unhandled Mermaid error prevented:", event.reason);
        event.preventDefault();
      }
    };
    window.addEventListener("unhandledrejection", this.unhandledRejectionHandler);
    try {
      await this.mermaidLoader.initializeMermaid();
      console.log("Modern Mermaid plugin loaded successfully");
    } catch (error) {
      console.error("Failed to initialize Mermaid:", error);
      new import_obsidian.Notice("Mermaid \uD50C\uB7EC\uADF8\uC778 \uCD08\uAE30\uD654 \uC2E4\uD328");
      return;
    }
    this.registerMarkdownCodeBlockProcessor("mer", async (source, el) => {
      try {
        const backgroundColor = this.settings.transparentMerBackground ? "transparent" : "#ffffff";
        await this.renderMermaid(source, el, "default", backgroundColor);
      } catch (error) {
        console.error("Mermaid code block processor error:", error);
      }
    });
    this.registerMarkdownCodeBlockProcessor("merlight", async (source, el) => {
      try {
        await this.renderMermaid(source, el, "default", "#ffffff");
      } catch (error) {
        console.error("Mermaid code block processor error:", error);
      }
    });
    this.registerMarkdownCodeBlockProcessor("merdark", async (source, el) => {
      try {
        await this.renderMermaid(source, el, "dark", "#000000");
      } catch (error) {
        console.error("Mermaid code block processor error:", error);
      }
    });
  }
  async renderMermaid(source, el, theme, backgroundColor) {
    await this.mermaidLoader.initializeMermaid();
    const mermaid = this.mermaidLoader.getMermaidInstance();
    if (!mermaid) {
      throw new Error("Mermaid not available");
    }
    const renderer = new MermaidRenderer(mermaid, this.settings);
    await renderer.render(source, el, theme, backgroundColor);
  }
  clearCache() {
    this.mermaidLoader.clearCache();
  }
  async saveSettings() {
    this.settingsManager.updateSettings(this.settings);
    await this.settingsManager.saveSettings();
  }
  onunload() {
    if (this.unhandledRejectionHandler) {
      window.removeEventListener("unhandledrejection", this.unhandledRejectionHandler);
      this.unhandledRejectionHandler = null;
    }
    MermaidRenderer.cleanupAllHandlers();
    this.mermaidLoader.cleanup();
    this.clearCache();
  }
};
var ModernMermaidSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Modern Mermaid Settings" });
    new import_obsidian.Setting(containerEl).setName("Mermaid Version").setDesc("Currently loaded Mermaid library version").addText((text) => text.setDisabled(true).setValue(this.plugin.settings.mermaidVersion));
    new import_obsidian.Setting(containerEl).setName("Enable Pan & Zoom").setDesc("Enable mouse wheel zoom and drag-to-pan for diagrams.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enablePanZoom).onChange(async (value) => {
      this.plugin.settings.enablePanZoom = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Double Click Zoom Level").setDesc("Zoom level when double-clicking on diagram (1 = original size, 2 = 2x, 3 = 3x). Click again to reset.").addSlider((slider) => slider.setLimits(1.5, 5, 0.5).setValue(this.plugin.settings.doubleClickZoomLevel).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.doubleClickZoomLevel = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Pan & Zoom Locked by Default").setDesc("Pan & zoom is locked by default. Click the lock button on the diagram to enable it. When locked, mouse wheel scrolls the document normally.").addToggle((toggle) => toggle.setValue(this.plugin.settings.panZoomLocked).onChange(async (value) => {
      this.plugin.settings.panZoomLocked = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable Touchpad Pan").setDesc("Enable two-finger horizontal/diagonal scrolling on touchpads for panning (when unlocked). Vertical scrolling uses Ctrl/Cmd + wheel for zoom.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableTouchpadPan).onChange(async (value) => {
      this.plugin.settings.enableTouchpadPan = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName('Transparent Background for "mer"').setDesc('Use transparent background for "mer" code blocks. Disable to use white background.').addToggle((toggle) => toggle.setValue(this.plugin.settings.transparentMerBackground).onChange(async (value) => {
      this.plugin.settings.transparentMerBackground = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Include Background in Copy").setDesc("Include background color when copying as image. Disable to copy only diagram.").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeBackgroundInCopy).onChange(async (value) => {
      this.plugin.settings.includeBackgroundInCopy = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Clear Cache").setDesc("Clear cached Mermaid library and force re-download").addButton((button) => button.setButtonText("Clear Cache").onClick(async () => {
      this.plugin.clearCache();
      this.plugin.settings.mermaidVersion = "Not loaded";
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Cache cleared. Please reload Obsidian to re-download Mermaid.");
      this.display();
    }));
  }
};
